### ISSUE TITLE
Missing observed data causes error in plotTimeSeriesResults()

### ISSUE THREAD

**Issue by woodwards** [florianhartig/BayesianTools#103]
When using plotTimeSeriesResults() to analyse the results, if there are NA in the observed values this will cause an error. I think this can be fixed by adding the following change to plotTimeSeriesResults():

    # missing data causes crash
    keeps <- which(!is.na(dh$scaledResiduals)) # which rows have data
    
    # residuals vs fitted
    DHARMa::plotResiduals(dh$fittedPredictedResponse[keeps], dh$scaledResiduals[keeps], main = "Residual vs. predicted\n quantile lines should be\n horizontal lines at 0.25, 0.5, 0.75", cex.main = 1, xlab = "Predicted value", ylab = "Standardized residual")
    
    # residuals vs time
    t <- 1:length(dh$fittedPredictedResponse)
    DHARMa::plotResiduals(t[keeps], dh$scaledResiduals[keeps], xlab = "Time", ylab = "Standardized residual", main = "Residual vs. time\n quantile lines should be\n horizontal lines at 0.25, 0.5, 0.75", cex.main = 1)

**Comment by florianhartig** [comment]
Thanks for the fix. Max, can you test this and build this in?

Note: duplicate with https://github.com/florianhartig/BayesianTools/issues/102 , close both when done

**Comment by florianhartig** [comment]
Max, wenn du was schließt am besten den commit erwähnen der das behebt, und wenn man im commit das Ticket erwähnt dann wird das auch gelinkt.

**Comment by MaximilianPi** [comment]
Alles klar, be3efa4f90c2db7ed02156853105e61018028b1d
