### ISSUE TITLE
Unit tests for marginal likelihood

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#105]
I would like to have a test for the ML calculations for a few cases where the exact solution is known analytically. This should also be an additional test for https://github.com/florianhartig/BayesianTools/issues/104

Max, can you implement at test for the marginalLikelihood function in R? What I have in mind would be to start with a multivariate normal density, with an option to chose dimensions.

* With wide uniform priors, the theoretical ML is simply the integral of the density (see Wikipedia)
* Set the same up in BayesianTool, wide uniform priors, MCMC sampling and then the various ML approximations 

What we want to know is how the ML approximation depends on 

* iterations (MCMC / other in the function)
* dimensions

**Comment by florianhartig** [comment]
In principle, I did this with https://github.com/florianhartig/BayesianTools/commit/e50350914736912c0a57c3c64abbe70e6886db01

Max, maybe you can take the help file, extend this a bit into a Rmd and place it into the informal test folder?

You could add a few more test, e.g. with the VSEM, and report how the methods compare. 

@TankredO - what I also noted is that the bridge sampling performs horribly - is there any chance that you have made an error when when interfacing to the package? Could you maybe check that this is equally bad when directly using the package? 

If these results are like that, I have no idea why one would bridge sample, it's sometimes even worse than the harmonic mean!

**Comment by MaximilianPi** [comment]
Done 158764b905009a5ab4a3862b27fefeeec9152114
