### ISSUE TITLE
Missing -Inf -> - Inf check in DEzs and DREAMzs with parallel = T

### ISSUE THREAD

**Issue by MaximilianPi** [florianhartig/BayesianTools#113]
DEzs and DREAMzs were missing a check for -Inf in the parallel execution. This created a problem when both the previous and the proposed value had the posterior of -Inf.

**Comment by MaximilianPi** [comment]
In the non parallel part of the code there was a check for this case:

```
if(!is.na(logfitness_x_prop[i,1] - logfitness_X[i,1]))
```
I added this to the parallel part and it is now working. 

ffeb3c2c40aec2a2e2c939197c5f98f273cc48ad

**Comment by MaximilianPi** [comment]
Question Florian: if -Inf -> - Inf, should we jump or not?

**Comment by MaximilianPi** [comment]
If the reason is what were outside the prior, no -> better warning
If the reason is likelihood, maybe ...

**Comment by MaximilianPi** [comment]
Prior Problem is moved to https://github.com/florianhartig/BayesianTools/issues/114

**Comment by florianhartig** [comment]
What I don't understand about our current solution

```
if(!is.na(logfitness_x_prop[i,1] - logfitness_X[i,1]))
```
also in the non-parallel case: when does this evaluate as true, and why? If everything goes right and our likelihood error catcher work (i.e. both likelihood and prior don't produce NAs), there are two cases I can think of:

- both prior and likelihood of one value produce -Inf -> evaluates to NaN in posterior, right?
- both proposal and current evaluate to -Inf

What I'm wondering about is if this this evaluation basically can't turn positive once the start values are within the prior ...

**Comment by MaximilianPi** [comment]
It turn's true when one of the two is not -Inf, and then only the following evaluation can be done: 
```
       if ((logfitness_x_prop[i,1] - logfitness_X[i,1] + r_extra[i]) > log(runif(1))){
           # accept <- accept + 1 
            X[i,] <- x_prop[i,]
            logfitness_X[i,] <- logfitness_x_prop[i,]
```
But I wonder, if the current is -Inf the proposal will never get accepted...Is this ok?

**Comment by florianhartig** [comment]
ah, no, I mean when is this turning false, so when is `logfitness_x_prop[i,1] - logfitness_X[i,1]` NA?

It seems to me that this cannot happen any more anyway, if we know that the start values for the likelihood are not -Inf, unless the start likelihood is -Inf, right?

Because na for a new value should be impossible, because if prior = -Inf, we dont' evaluate the likelihood, and if not, a likelihood should produce maximally -Inf, which evaluates as inf and not NA

So, by that logic, we could remove these statements entirely, if we ensure that the start likelihoods are not Inf ...

**Comment by MaximilianPi** [comment]
-Inf - -Inf = NaN
Yes, it's related to https://github.com/florianhartig/BayesianTools/issues/114#issuecomment-379054992
If we me make sure that the start values are inside.
(example for the problem here:
```
> logfitness_x_prop
[1] -Inf -Inf -Inf
> logfitness_X
      posterior likelihood     prior
[1,] -11.995876  -7.893245 -4.102631
[2,]  -8.758247  -4.507571 -4.250676
[3,]       -Inf         NA      -Inf

#for i = 3 
 > logfitness_x_prop[1] - logfitness_X[3,1]
posterior 
      NaN 

```

**Comment by MaximilianPi** [comment]
I will close this issue because it is now running and the real cause is related to #87 and #114
