### ISSUE TITLE
Create a check of start values / check matrix at the runMCMC level

### ISSUE THREAD

**Issue by MaximilianPi** [florianhartig/BayesianTools#114]
Before starting the actual MCMCs, check if start values are inside the prior! If not, throw a warning. This should be done irrespective of the sampler, so do this at runMCMC level. Also for other things like the z Matrix

See also https://github.com/florianhartig/BayesianTools/issues/113

**Comment by TankredO** [comment]
Before starting to work on this we should think about the pre-optimization since these issues are coupled #87

**Comment by florianhartig** [comment]
I think it's sensible to implement an allInsidePrior function in the createPrior, and then just call it if needed. 

It's not compulsory to do the pre-optimization, and the pre-optim is outside the algorithms. For me, it makes sense if the algorithms check if their start values are sensible. 

Max, do you know how I imagine this with the class function?

**Comment by MaximilianPi** [comment]
So what shall we do? 
1. create a check function allInsidePrior in createPrior and give it to the prior
-> a) call it in the sampler function, e.g. in DEzs after filling the Z-Matrix 
     b) call it during the sampling after n jumps are rejected consecutively 
 
2. Or we just give a warning when n times new proposals are rejected consecutively (due to bad start values/priors...)

**Comment by florianhartig** [comment]
1. Create the function during Prior Setup (+ unit tests)
2. Call this function on all start values, as early as possible (I'm not sure, if z matrix is not provided, when is it created, in the runMCMC or later? if possible, I would check start values already at the runMCMC level)

**Comment by MaximilianPi** [comment]
solved 78174f6d3ead7a2446db2b35c540ed9dcac976b7
