### ISSUE TITLE
pass on parameters of likelihood / prior via ... in createBayesianSetup

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#117]
this is an endless story, but related to https://github.com/florianhartig/BayesianTools/issues/115 and https://github.com/florianhartig/BayesianTools/issues/98, it occurred to me that we might make things a lot easier when we change the setup signature to 

createBayesianSetup(likelihood, prior, otherThings, ...)

and then pass on ... to likelihood and prior. In this way, the idea would be that the user either

- provides explicit classes for likelihood and prior, or
- densities for likelihood and prior, and additional parameters to createLikelihood, createPrior are passed on via ... (we just have to make sure that variable names do not collide)

The only exception might be the parallel stuff, because if we want to parallelize several MCMC runs, as we discussed, we might want to have the cluster information at the setup level (although we could keep the tradition to attach parallel info to the likelihood, and just probe if such info exists from the setup)

**Comment by TankredO** [comment]
solved with #124

**Comment by woodwards** [comment]
So how do you pass parameters into the likelihood function?

**Comment by woodwards** [comment]
I got it working using the `parallel::makeCluster(n)` approach and `parallel::clusterExport()`.

[relevant documentation is here](https://github.com/florianhartig/BayesianTools/blob/3a17045066fe9592353fe12c53565bf8e4b55ee5/BayesianTools/vignettes/BayesianTools.Rmd)
