### ISSUE TITLE
Bad performance of bridge sampling

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#121]
@TankredO - what I also noted in https://github.com/florianhartig/BayesianTools/issues/105 is that the bridge sampling performs horribly - is there any chance that you have made an error when when interfacing to the package? Could you maybe check that this is equally bad when directly using the package?

If these results are like that, I have no idea why one would bridge sample, it's sometimes even worse than the harmonic mean!

**Comment by TankredO** [comment]
@MaximilianPi you had also a look at this, right? Did you find anything? I couldn't find a bug in our code and in how we use the bridgeSampling package.

**Comment by florianhartig** [comment]
Could you maybe place an example / test file in the manual test folder, where a BT application of the bridge sampling is compared with a native application, e.g. from their help, or just sample the examples in the marginalLikelihood help with the package, without using BT.

**Comment by florianhartig** [comment]
If the results remain, we should display a message for bridge and harmonic mean, warning the user that the chosen methods is numerically unstable.

**Comment by MaximilianPi** [comment]
solved b9a70217fe7c77db3166b7f04db69714bb455258
