### ISSUE TITLE
getSample in plot

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#126]
Hi Tankred,

I have the feeling the getSample arguments are not properly passed on in plot, try changing the start in 

```
# likelihood sampled with flat prior 

ll = function(x) sum(dnorm(x, log = TRUE))
setup = createBayesianSetup(ll, lower = c(-100,-100), upper = c(100,100))
out <- runMCMC(bayesianSetup = setup, sampler = "DEzs")
summary(out)

marginalPlot(out, plotPrior = F, start = 1000)
```

**Comment by florianhartig** [comment]
Also, try changing prior = T / F i this, this does not only switch the prior, but also the plot type

**Comment by TankredO** [comment]
It would be the best to rewrite the marginalPLot function sometime. When I worked on this, I just added new functionality to the existing funciton. But I think the whole thing is quite confusing to work with.

**Comment by florianhartig** [comment]
but the getSample should just be the first line, if you extract the sample, right?

**Comment by TankredO** [comment]
Yes, sure for getSample it should be no problem.

**Comment by florianhartig** [comment]
Hi Tankred, can you have a look at this?

**Comment by TankredO** [comment]
74f173a0857ea508e2290b205d1e931867c8c1b7

**Comment by florianhartig** [comment]
are all problems solved? Can we close this?
