### ISSUE TITLE
Finalize 0.1.5 Release

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#131]
Hi guys,

good work - I think we're getting ready for the 0.1.5 release, I think the issues that remain can be solved relatively quicly. 

This issue is just a reminder for last things to check and as a discussion thread for what needs to be done in general before the release.

**Comment by florianhartig** [comment]
OK, I kicked the can down the road with https://github.com/florianhartig/BayesianTools/issues/12 and moved this to 0.1.6, so we should be good to go with the 0.1.5 release ... open question is still the licence and to check everything.

**Comment by MaximilianPi** [comment]
0.1.5 is on CRAN now
