### ISSUE TITLE
problems with marginalPlot()

### ISSUE THREAD

**Issue by fkrauer** [florianhartig/BayesianTools#138]
Hi

I am not able to plot the prior and marginal posteriors of my bayesianOutput (DEzs) with _marginalPlot()_.

`marginalPlot(out, start=nburn, plotPrior=T)` 

yields the unscaled violin plots of the posterior. I can't see the prior densities though. I also don't see a visual difference if I omit _start=nburn_

`marginalPlot(out, scale=T, start=nburn, plotPrior=T` 

results in an error: **Error in as.graphicsAnnot(main) : object 'main' not found**.  Apparently there is an issue with the scaling and with the plotting of the prior and maybe also with the burn-in. Any ideas why this happens? Out is the raw output of _runMCMC()_ .

Thanks a lot
Fabienne

**Comment by florianhartig** [comment]
I assume that this is with the development version of BT?

**Comment by fkrauer** [comment]
I am using BayesianTools 0.1.3. I'll check the latest version. Thanks!
