### ISSUE TITLE
font size of correlation coefficient in correlationPlot()

### ISSUE THREAD

**Issue by fkrauer** [florianhartig/BayesianTools#139]
Hi

Is it possible to increase the font size of the correlation coefficient in the correlationPlot() function? Low correlation coefficients yield really tiny prints. I am not sure about the added value of having a font size correlated with the magnitude of the coefficient. I'd prefer to have the same font size.

Best wishes, Fabienne

**Comment by florianhartig** [comment]
I've implemented an option to suppress this - it's in the development branch of BT

**Comment by florianhartig** [comment]
For further modifications, it's probably easiest to use the code (type correlationPlot in the console) and modify the text size by hand
