### ISSUE TITLE
Large amounts of warnings in RStudio Check

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#14]
There are many warnings in RStudio Check that need to be resolved for CRAN.

Mostly, these are import problems with 

`no visible global function definition for ...`

see solution here http://stackoverflow.com/questions/31132552/no-visible-global-function-definition-for-median

**Comment by stefan-paul** [comment]
Very strange,
I'm not getting these warnings in the check.
For me only the testthat files throw an error for arch 'i386' for the parallel examples.
However for arch 'x64' everything's running fine.
If I'm not running the tests I'm getting neither errors nor warnings in the 
RStudio check.

**Comment by florianhartig** [comment]
These are no unit testing errors, these are general R check warnings that will be treated as errors from CRAN

I get the same warnings from https://travis-ci.org/florianhartig/BayesianTools/

(btw, every push will automatically rerun all checks)

If you don't get the warnings, maybe the settings of your RStudio checks, are they on full CRAN tests?

**Comment by stefan-paul** [comment]
I'm running the check "--as-cran". Do I need to add any other argument?

In the travis test I only see one warning:
DREAMzs: no visible binding for global variable ‘xOld’
this should be removed with https://github.com/florianhartig/BayesianTools/commit/a0c3e2b1fff6750ae53f9c360c5cd708dfdc96f7

**Comment by florianhartig** [comment]
OK, this is what I get - you get nothing of those 

`
==> Rcpp::compileAttributes()

* Updated src/RcppExports.cpp
* Updated R/RcppExports.R

==> devtools::check(args = c('--as-cran'))

Updating BayesianTools documentation
Loading BayesianTools
Re-compiling BayesianTools
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/Users/Florian/Home/Projekte/Papers_in_Progress/16-BayesianPackage/BayesianTools/BayesianTools'  \
  --library='/var/folders/0b/z4_cv_xx26bgzwvyyr1tgsyc0000gp/T//Rtmpsop2rF/devtools_install_14cf12433f064'  \
  --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec  \
  --no-multiarch --no-test-load 

* installing *source* package ‘BayesianTools’ ...
** libs
clang++ -arch x86_64 -ftemplate-depth-256 -I/Library/Frameworks/R.framework/Resources/include        -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -mtune=core2  -O3       -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -ftemplate-depth-256 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o BayesianTools.so RcppExports.o vsem.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /private/var/folders/0b/z4_cv_xx26bgzwvyyr1tgsyc0000gp/T/Rtmpsop2rF/devtools_install_14cf12433f064/BayesianTools/libs
* DONE (BayesianTools)
Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building BayesianTools ---------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build  \
  '/Users/Florian/Home/Projekte/Papers_in_Progress/16-BayesianPackage/BayesianTools/BayesianTools'  \
  --no-resave-data --no-manual 

* checking for file ‘/Users/Florian/Home/Projekte/Papers_in_Progress/16-BayesianPackage/BayesianTools/BayesianTools/DESCRIPTION’ ... OK
* preparing ‘BayesianTools’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘BayesianTools_0.0.10.0.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking BayesianTools ---------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/0b/z4_cv_xx26bgzwvyyr1tgsyc0000gp/T//Rtmpsop2rF/BayesianTools_0.0.10.0.tar.gz'  \
  --as-cran --timings --as-cran --no-manual 

* using log directory ‘/Users/Florian/Home/Projekte/Papers_in_Progress/16-BayesianPackage/BayesianTools/BayesianTools.Rcheck’
* using R version 3.3.1 (2016-06-21)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘BayesianTools/DESCRIPTION’ ... OK
* this is package ‘BayesianTools’ version ‘0.0.10.0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘BayesianTools’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘examples’
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... WARNING
Found a .Internal call in the following function:
  ‘rmBayesianSetup’
with calls to .Internal functions
  ‘remove’

Packages should not call .Internal(): it is not part of the API, for
use only by R itself and subject to change without notice.

In addition to the above warning(s), found the following notes:

AM: no visible global function definition for ‘runif’
AM: no visible global function definition for ‘cov’
DE.MC: no visible global function definition for ‘modifyList’
DE.MC: no visible global function definition for ‘rnorm’
DE.MC: no visible global function definition for ‘runif’
DE.MC: no visible global function definition for ‘flush.console’
DE.MCzs: no visible global function definition for ‘modifyList’
DE.MCzs: no visible global function definition for ‘runif’
DE.MCzs: no visible global function definition for ‘rnorm’
DE.MCzs: no visible global function definition for ‘flush.console’
DIC: no visible global function definition for ‘var’
DR: no visible global function definition for ‘runif’
DRAM: no visible global function definition for ‘runif’
DRAM: no visible global function definition for ‘cov’
DREAM: no visible global function definition for ‘runif’
DREAM: no visible global function definition for ‘rnorm’
DREAM: no visible binding for global variable ‘sd’
DREAM: no visible global function definition for ‘quantile’
DREAM: no visible global function definition for ‘flush.console’
DREAMzs: no visible global function definition for ‘runif’
DREAMzs: no visible global function definition for ‘rnorm’
DREAMzs: no visible binding for global variable ‘sd’
DREAMzs: no visible global function definition for ‘quantile’
DREAMzs: no visible global function definition for ‘flush.console’
M: no visible global function definition for ‘runif’
Twalk: no visible global function definition for ‘runif’
Twalk: no visible global function definition for ‘flush.console’
Twalksteps: no visible global function definition for ‘runif’
VSEMcreateLikelihood: no visible global function definition for ‘rnorm’
VSEMcreateLikelihood: no visible global function definition for ‘par’
VSEMcreateLikelihood : likelihood: no visible global function
  definition for ‘dnorm’
VSEMcreatePAR: no visible global function definition for ‘rnorm’
WAIC: no visible binding for global variable ‘var’
applySettingsDefault: no visible global function definition for
  ‘sessionInfo’
betaFun: no visible global function definition for ‘runif’
calc_mpsrf: no visible global function definition for ‘window’
calc_mpsrf: no visible global function definition for ‘start’
calc_mpsrf: no visible binding for global variable ‘var’
calc_mpsrf: no visible global function definition for ‘var’
correlationPlot : panel.hist.dens: no visible global function
  definition for ‘par’
correlationPlot : panel.hist.dens: no visible global function
  definition for ‘hist’
correlationPlot : panel.hist.dens: no visible global function
  definition for ‘rect’
correlationPlot : panel.cor: no visible global function definition for
  ‘par’
correlationPlot : panel.cor: no visible global function definition for
  ‘cor’
correlationPlot : panel.cor: no visible global function definition for
  ‘strwidth’
correlationPlot : panel.cor: no visible global function definition for
  ‘text’
correlationPlot : plotEllipse: no visible global function definition
  for ‘par’
correlationPlot : plotEllipse: no visible global function definition
  for ‘polygon’
correlationPlot : correlationEllipse : ToRGB: no visible global
  function definition for ‘rgb’
correlationPlot : correlationEllipse: no visible global function
  definition for ‘colorRampPalette’
correlationPlot: no visible global function definition for ‘pairs’
correlationPlot : <anonymous>: no visible global function definition
  for ‘par’
createBetaPrior : density: no visible global function definition for
  ‘dbeta’
createBetaPrior : sampler: no visible global function definition for
  ‘rbeta’
createPriorDensity: no visible global function definition for ‘cov’
createProposalGenerator : samplingFunction: no visible global function
  definition for ‘rnorm’
createProposalGenerator : returnDensity: no visible global function
  definition for ‘dnorm’
createUniformPrior : density: no visible global function definition for
  ‘dunif’
createUniformPrior : sampler: no visible global function definition for
  ‘runif’
generateCRvalues: no visible global function definition for ‘rmultinom’
generateParallelExecuter: no visible global function definition for
  ‘modifyList’
generateTestDensityMultiNormal: no visible global function definition
  for ‘runif’
generateTestDensityMultiNormal: multiple local function definitions for
  ‘out’ with different formal arguments
getCredibleIntervals : <anonymous>: no visible global function
  definition for ‘quantile’
getRmvnorm: no visible global function definition for ‘rnorm’
getSample.data.frame: possible error in getSample(as.matrix(data),
  parametersOnly = parametersOnly, coda = coda, start = start, end =
  end, thin = thin, whichParameters = whichParameters,
  includesProbabilities = includesProbabilities, reportDiagnostics =
  reportDiagnostics): unused argument (includesProbabilities =
  includesProbabilities)
likelihoodIidNormal: no visible global function definition for ‘dnorm’
marginalLikelihood: no visible global function definition for ‘cov’
marginalPlot: no visible global function definition for ‘axis’
marginalPlot: no visible global function definition for ‘points’
mpsrf: no visible global function definition for ‘start’
mpsrf: no visible global function definition for ‘end’
plotTimeSeries: no visible global function definition for ‘polygon’
plotTimeSeries: no visible global function definition for ‘lines’
plotTimeSeries: no visible global function definition for ‘points’
plotTimeSeriesResiduals: no visible global function definition for
  ‘barplot’
print.mcmcSampler: no visible global function definition for ‘methods’
print.mcmcSamplerList: no visible global function definition for
  ‘methods’
print.smcSampler: no visible global function definition for ‘methods’
print.smcSamplerList: no visible global function definition for
  ‘methods’
propFun: no visible global function definition for ‘runif’
propFun: no visible global function definition for ‘rnorm’
sampleMetropolis: no visible global function definition for ‘runif’
sampleMetropolis: no visible global function definition for
  ‘flush.console’
setupStartProposal: no visible global function definition for ‘optim’
smcSampler: no visible global function definition for ‘runif’
summary.mcmcSampler: no visible global function definition for ‘cor’
summary.mcmcSampler: no visible global function definition for
  ‘quantile’
summary.mcmcSamplerList: no visible global function definition for
  ‘cor’
summary.mcmcSamplerList: no visible global function definition for
  ‘quantile’
testDensityNormal: no visible global function definition for ‘dnorm’
updateGroups: no visible global function definition for ‘cor’
updateGroups: no visible global function definition for ‘hclust’
updateGroups: no visible global function definition for ‘as.dist’
updateGroups: no visible global function definition for ‘cutree’
updateProposalGenerator: no visible global function definition for
  ‘cov’
updateProposalGenerator: no visible global function definition for
  ‘var’
Undefined global functions or variables:
  as.dist axis barplot colorRampPalette cor cov cutree dbeta dnorm
  dunif end flush.console hclust hist lines methods modifyList optim
  pairs par points polygon quantile rbeta rect rgb rmultinom rnorm
  runif sd sessionInfo start strwidth text var window
Consider adding
  importFrom("grDevices", "colorRampPalette", "rgb")
  importFrom("graphics", "axis", "barplot", "hist", "lines", "pairs",
             "par", "points", "polygon", "rect", "strwidth", "text")
  importFrom("stats", "as.dist", "cor", "cov", "cutree", "dbeta",
             "dnorm", "dunif", "end", "hclust", "optim", "quantile",
             "rbeta", "rmultinom", "rnorm", "runif", "sd", "start",
             "var", "window")
  importFrom("utils", "flush.console", "methods", "modifyList",
             "sessionInfo")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  19: lapply(cl[1:jobs], recvResult)
  20: FUN(X[[i]], ...)
  21: recvData(con)
  22: recvData.SOCKnode(con)
  23: unserialize(node$con)
  
  testthat results ================================================================
  OK: 205 SKIPPED: 0 FAILED: 2
  1. Error: 2-d with parallel chains works (@test-workflow.R#143) 
  2. Error: 2-d with parallel chains and restart works (@test-workflow.R#170) 
  
  Error: testthat unit tests failed
  Execution halted
* checking for unstated dependencies in vignettes ... [55s/70s]
 OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* DONE
Status: 1 ERROR, 1 WARNING, 1 NOTE

See
  ‘/Users/Florian/Home/Projekte/Papers_in_Progress/16-BayesianPackage/BayesianTools/BayesianTools.Rcheck/00check.log’
for details.

checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  19: lapply(cl[1:jobs], recvResult)
  20: FUN(X[[i]], ...)
  21: recvData(con)
  22: recvData.SOCKnode(con)
  23: unserialize(node$con)
  
  testthat results ================================================================
  OK: 205 SKIPPED: 0 FAILED: 2
  1. Error: 2-d with parallel chains works (@test-workflow.R#143) 
  2. Error: 2-d with parallel chains and restart works (@test-workflow.R#170) 
  
  Error: testthat unit tests failed
  Execution halted

checking R code for possible problems ... WARNING
Found a .Internal call in the following function:
  ‘rmBayesianSetup’
with calls to .Internal functions
  ‘remove’

Packages should not call .Internal(): it is not part of the API, for
use only by R itself and subject to change without notice.

In addition to the above warning(s), found the following notes:
... 142 lines ...
Consider adding
  importFrom("grDevices", "colorRampPalette", "rgb")
  importFrom("graphics", "axis", "barplot", "hist", "lines", "pairs",
             "par", "points", "polygon", "rect", "strwidth", "text")
  importFrom("stats", "as.dist", "cor", "cov", "cutree", "dbeta",
             "dnorm", "dunif", "end", "hclust", "optim", "quantile",
             "rbeta", "rmultinom", "rnorm", "runif", "sd", "start",
             "var", "window")
  importFrom("utils", "flush.console", "methods", "modifyList",
             "sessionInfo")
to your NAMESPACE file.

checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘examples’
R CMD check results
1 error  | 1 warning  | 1 note 

R CMD check succeeded
`

**Comment by florianhartig** [comment]
Same problem in https://travis-ci.org/florianhartig/BayesianTools/jobs/193116389

**Comment by stefan-paul** [comment]
No... (I removed the parallel examples in the tests here as they throw an error):


==> devtools::check(args = c('--as-cran'))

Updating BayesianTools documentation
Loading BayesianTools
Writing NAMESPACE
Writing generateParallelExecuter.Rd
Writing BayesianTools.Rd
Writing DIC.Rd
Writing MAP.Rd
Writing vsemC.Rd
Writing smcSampler.Rd
Writing VSEM.Rd
Writing VSEMgetDefaults.Rd
Writing createMixWithDefaults.Rd
Writing VSEMcreatePAR.Rd
Writing VSEMcreateLikelihood.Rd
Writing WAIC.Rd
Writing updateGroups.Rd
Writing getBlock.Rd
Writing getBlockSettings.Rd
Writing getSample.Rd
Writing createBayesianSetup.Rd
Writing checkBayesianSetup.Rd
Writing rmBayesianSetup.Rd
Writing createLikelihood.Rd
Writing likelihoodIidNormal.Rd
Writing likelihoodAR1.Rd
Writing createMcmcSamplerList.Rd
Writing createPosterior.Rd
Writing createPrior.Rd
Writing createUniformPrior.Rd
Writing createTruncatedNormalPrior.Rd
Writing createBetaPrior.Rd
Writing createPriorDensity.Rd
Writing createSmcSamplerList.Rd
Writing combineChains.Rd
Writing makeObjectClassCodaMCMC.Rd
Writing convertCoda.Rd
Writing gelmanDiagnostics.Rd
Writing marginalLikelihood.Rd
Writing getCredibleIntervals.Rd
Writing getPredictiveDistribution.Rd
Writing getPredictiveIntervals.Rd
Writing DE.MC.Rd
Writing DE.MCzs.Rd
Writing DREAM.Rd
Writing generateCRvalues.Rd
Writing AdaptpCR.Rd
Writing DREAMzs.Rd
Writing M.Rd
Writing AM.Rd
Writing DR.Rd
Writing DRAM.Rd
Writing Metropolis.Rd
Writing sampleMetropolis.Rd
Writing mcmcMultipleChains.Rd
Writing runMCMC.Rd
Writing applySettingsDefault.Rd
Writing setupStartProposal.Rd
Writing getPossibleSamplerTypes.Rd
Writing Twalk.Rd
Writing TwalkMove.Rd
Writing Twalksteps.Rd
Writing sumSquare.Rd
Writing propFun.Rd
Writing betaFun.Rd
Writing Gfun.Rd
Writing correlationPlot.Rd
Writing marginalPlot.Rd
Writing plotSensitivity.Rd
Writing plotTimeSeries.Rd
Writing plotTimeSeriesResiduals.Rd
Writing plotTimeSeriesResults.Rd
Writing tracePlot.Rd
Writing createProposalGenerator.Rd
Writing updateProposalGenerator.Rd
Writing getRmvnorm.Rd
Writing factorMatrice.Rd
Writing generateTestDensityMultiNormal.Rd
Writing testDensityBanana.Rd
Writing testDensityNormal.Rd
Writing testLinearModel.Rd
Writing testDensityInfinity.Rd
Writing logSumExp.Rd
Writing thinMatrix.Rd
Writing scaleMatrix.Rd
Writing metropolisRatio.Rd
Writing getPanels.Rd
Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building BayesianTools ---------------------------------------------------------
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD build  \
  "C:\Users\Stefan\Desktop\BayesianTools\BayesianTools\BayesianTools"  \
  --no-resave-data --no-manual 

* checking for file 'C:\Users\Stefan\Desktop\BayesianTools\BayesianTools\BayesianTools/DESCRIPTION' ... OK
* preparing 'BayesianTools':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building 'BayesianTools_0.0.10.0.tar.gz'

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking BayesianTools ---------------------------------------------------------
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD check  \
  "C:\Users\Stefan\AppData\Local\Temp\RtmpIxgoMr/BayesianTools_0.0.10.0.tar.gz"  \
  --as-cran --timings --as-cran 

* using log directory 'C:/Users/Stefan/Desktop/BayesianTools/BayesianTools/BayesianTools.Rcheck'
* using R version 3.2.2 (2015-08-14)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using option '--as-cran'
* checking for file 'BayesianTools/DESCRIPTION' ... OK
* this is package 'BayesianTools' version '0.0.10.0'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'BayesianTools' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  'examples'
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
generateTestDensityMultiNormal: multiple local function definitions for
  'out' with different formal arguments
getSample.data.frame: possible error in getSample(as.matrix(data),
  parametersOnly = parametersOnly, coda = coda, start = start, end =
  end, thin = thin, whichParameters = whichParameters,
  includesProbabilities = includesProbabilities, reportDiagnostics =
  reportDiagnostics): unbenutztes Argument (includesProbabilities =
  includesProbabilities)
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... OK
** running examples for arch 'x64' ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
** running tests for arch 'i386' ...
  Running 'testthat.R' OK
** running tests for arch 'x64' ... [34s]

  Running 'testthat.R' OK
 [36s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ...
   'BayesianTools.Rmd' ... OK
   'ReferenceManual.Rmd' ... OK
 OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
Status: 2 NOTEs

See
  'C:/Users/Stefan/Desktop/BayesianTools/BayesianTools/BayesianTools.Rcheck/00check.log'
for details.



R CMD check succeeded

**Comment by florianhartig** [comment]
I would venture a guess that either your R, Studio, or devtools is old? I would update all of them - we should test on the latest R version anyway

**Comment by stefan-paul** [comment]
Ok I'll update all my versions.

**Comment by stefan-paul** [comment]
Should be done with https://github.com/florianhartig/BayesianTools/commit/bd205247fba9aa93cc3f458b136c2807bd1b2364 .
