### ISSUE TITLE
suggestion for marginalPlot()

### ISSUE THREAD

**Issue by fkrauer** [florianhartig/BayesianTools#140]
Hi

This is not an issue, but a suggestion for marginalPlot():

How about displaying only the upper part of the violins (like the a usual density plots) and adding an option to tune the alpha value of the plot colour setting for prior and posterior?

I was thinking about something like here (without the likelihood obviously):
https://m-clark.github.io/bayesian-basics/a-hands-on-example.html

Best, Fabienne

**Comment by florianhartig** [comment]
Hi Fabienne, do you have the latest (development) version of BT? Because it seems to me that we have this type of plots already, e.g. 

```
## Generate a test likelihood function. 
ll <- generateTestDensityMultiNormal(sigma = "no correlation")

## Create a BayesianSetup object from the likelihood 
## is the recommended way of using the runMCMC() function.
bayesianSetup <- createBayesianSetup(likelihood = ll, lower = rep(-10, 3), upper = rep(10, 3))

## Finally we can run the sampler and have a look
settings = list(iterations = 1000, adapt = FALSE)
out <- runMCMC(bayesianSetup = bayesianSetup, sampler = "Metropolis", settings = settings)


marginalPlot(out)
marginalPlot(out, plotPrior = F)
marginalPlot(out, histogram = T)
marginalPlot(out, singlePanel = T, scale=T, col = c("red", "blue"))
```

![image](https://user-images.githubusercontent.com/5457753/41128282-e9302802-6aad-11e8-9e11-24d5df099d52.png)


![image](https://user-images.githubusercontent.com/5457753/41128323-0acda9ee-6aae-11e8-9dc2-811f2cf7eae8.png)

**Comment by fkrauer** [comment]
oh great, this is pretty much what I was looking for. Will check out the latest version. I was using 0.1.3. Thanks!

**Comment by florianhartig** [comment]
best to install the development version from github, I think these plots are not yet in the CRAN version
