### ISSUE TITLE
Histogram option in marginalPlot does not work

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#141]
through https://github.com/florianhartig/BayesianTools/issues/140 , I update the help for marginalPlot, and noted that the histogram option doesn't work as expected. 

We should be able to switch between 

- violin
- distribution
- distrib + hist

**Comment by MaximilianPi** [comment]
1c12fb42930a82e1a89530b717b630cb0dfa9cc4
I also have fixed the plotBest option
