### ISSUE TITLE
Plot help

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#142]
Max, can you check / extend the plot help functions? I note they are very basic. In particular

- filename should always functionnameHelp.R
- help file should show a variety of options to use the function (at the moment very basic)

Could you maybe at the same time check that all function options are also used in the checks. Maybe create a new plot check file, if it's not there yet.

**Comment by MaximilianPi** [comment]
done 1c12fb42930a82e1a89530b717b630cb0dfa9cc4
- help files were extended
- help files were renamed
- tests were added for correlationPlot + extension of other tests
