### ISSUE TITLE
Error in parallel setting when using Rcpp code

### ISSUE THREAD

**Issue by fkrauer** [florianhartig/BayesianTools#148]
Hi

I am running a dynamic model, of which parts are coded in C++ to speed things up. I am using Rcpp to integrate it with R. The fitting of this model works fine without the parallel setting, but when i try to run it on multiple cores, it throws me an error:

`Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: NULL value passed as symbol address`

Any idea where this error stems from? Could it be that the .cpp code is not passed on to every node? 

I setup the parallel fitting with the following settings:

`  opts <- list(packages=list("BayesianTools", "deSolve", "Rcpp"), 
               variables=list("data", "initmodel", "season_model_meta", "loglik", "rfunc", "mufunc", "epsilonfunc", "tempfunc", "siirdysismeta", "ysmodel", "theta", "inits", "patchintro", "nintro", "t", "M", "solver", "climsummary", "est.index"), 
               dlls=NULL)`
  
  `bayesianSetup <- createBayesianSetup(prior = prior,
                                       likelihood = loglikwrap,
                                       names = names(theta[est.index]),
                                       parallel = cpus,
                                       parallelOptions = opts)`

where `siirdysismeta` and `ysmodel` are the functions coded in C++.  I am using BT 0.1.4 (the one on cran) and Rcpp_0.12.12.

Thanks and best wishes, Fabienne

**Comment by florianhartig** [comment]
Could be any number of things. I'd suggest to boil this down

a) check out if your code can actually be parallelized in R, e.g. running a foreach loop or so ... sometimes C code is not save for parallelization (global variables and that kind of things) ... have you run this code in parallel before?

b) check out if the likelihood in the BayesianSetup can be evaluated in parallel, and delivers sensible results

**Comment by fkrauer** [comment]
The use of .cpp code on a cluster works if it is wrapped as an R-package (with `Rcpp.package.skeleton()`) and then included in the BayesianSetup parallel options with the `packages `argument. However, I get a new error now

`Error in if ((logfitness_x_prop[i, 1] - logfitness_X[i, 1] + r_extra[i]) >  : 
  missing value where TRUE/FALSE needed`

I think other people have had this error too with the parallel option (independent whether they use .cpp code or not). Is this an open issue in the current version 0.1.4 of BT?

Thanks, Fabienne

**Comment by MaximilianPi** [comment]
Hi Fabienne,
yes it's a known issue with the 0.1.4 CRAN version, so if you install the development version it should work.

**Comment by fkrauer** [comment]
Great, thanks. Will try the development version.
