### ISSUE TITLE
narrow posteriors not shown on marginalPlot()

### ISSUE THREAD

**Issue by fkrauer** [florianhartig/BayesianTools#149]
Hi

I am using the dev version of BT (0.1.4). I noticed that if the posteriors are very narrow compared to the range of their priors, they don't show with `marginalPlot()`. It can be circumvented by manually increasing the `n` parameter in the `density()` function (has to be a power of 2). You might want to add a note in the vignette or include an argument in `marginalPlot()` to tweak it (maybe with a warning about increasing computational time :-)). 

Best, Fabienne

**Comment by MaximilianPi** [comment]
Hi Fabienne,
the marginalPlot function was reworked by @TankredO . You can check it out with the new BT devel version
