### ISSUE TITLE
docs in BT folder

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#155]
Hi Tankred,

there was a docs folder in the BT (not the main folder) - I removed this in https://github.com/florianhartig/BayesianTools/commit/d88689ba3a3d82e562f9e7c0440b728690f1fbc8 because I assume that this was an error (there is also the docs folder in the root)

Can you confirm?

**Comment by TankredO** [comment]
Should be fine, I guess that happened when merging Thema master und development branch.

**Comment by TankredO** [comment]
Maybe we should move the pkgdown stuff in another repository?
