### ISSUE TITLE
marginal plot

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#156]
there's a global variable flying around in the marginalPlot function, can you have a look?

Status: 1 NOTE
checking R code for possible problems ... NOTE
marginalPlotDensity: warning in axis(1, at = xrange[, i], labels = NA,
  lwd.tick = 0): partial argument match of 'lwd.tick' to 'lwd.ticks'
marginalPlotViolin: warning in axis(1, at = xrange[, i], labels = NA,
  lwd.tick = 0): partial argument match of 'lwd.tick' to 'lwd.ticks'
marginalPlot: no visible binding for global variable
  ‘marginalPlotHistogram’
Undefined global functions or variables:
  marginalPlotHistogram

**Comment by MaximilianPi** [comment]
1fdd1ad335149d21d637e2e59de7bfc6ea14da25, try again
