### ISSUE TITLE
Error in summary() - "Error in chol.default(W) :   the leading minor of order 2 is not positive definite"

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#166]
From a user:

ich versuche zurzeit mittels deines Baysian R-Skripts (BayesianTools) mein
Simulationsmodell zu kalibrieren. Dabei erhalte ich nahezu immer folgende
Fehlermeldung, wenn ich mir die Summary von runMCMC ausgeben lassen
möchte:

"Error in chol.default(W) :
  the leading minor of order 2 is not positive definite"

Mein Settings dazu sind (Dabei ist es irrelavant, wie viele Iterationen
ich habe):
settings <- list(iterations = 300, message = TRUE)
mcmcout <- runMCMC(bayesianSetup = bayesianSetup, sampler = "DEzs",
settings = settings)"

Ich hatte erfreulicherweise gesehen, dass du schon einmal Bezug zu diesem
Problem genommen hattest
(https://github.com/florianhartig/BayesianTools/issues/90) und möchte
daher fragen, ob du dafür eine Lösung gefunden hast?

**Comment by florianhartig** [comment]
Hi,

no, this is not related to #90 - I loaded in your data, and the problem is that the calculation of the Gelman diagnostics that are done by the summary function fail, presumably because this is an extremely short chain that does not mix very well (see trace plot below).

The problem should go away if you run the sampler for longer. Nevertheless, we should catch and suppress this error.  

![image](https://user-images.githubusercontent.com/5457753/46290875-b27aee80-c595-11e8-8e13-18cabef47908.png)

**Comment by KatharinaZi** [comment]
Hi Florian,

thanks for your fast help and answer. It works!  However, at first I did the simulation with 10000 iteration on my slow computer (Windows 8) and I've got the same error message. So, I try to run the calibration on an other pc (Ubuntu 16.04) and it happily works.

**Comment by florianhartig** [comment]
Hi Katharina,

glad it works - the DEzs is usually relatively reliable, but it can get problems if your prior is very different from the posterior, as we generate start values for the prior. If you continue to have problems with that, have a look at https://github.com/florianhartig/BayesianTools/issues/79

**Comment by rtrepos** [comment]
Hi, 
I have the same error with the sampler DREAM with a relative important (is it enough ?) length of chains:

5 chains with 2000 points => n = 10000

Then gelmanDiagnostics send me this error (in french) :

Error in chol.default(W) : 
  le mineur dominant d'ordre 4 n'est pas défini positif

Best
Ronan

**Comment by florianhartig** [comment]
Hi Ronan,

the  reason is with near certainty that your sampler doesn't mix well, so that you don't have enough variance in the chain. Run your sampler longer, or start it with better choices for the Z matrix.

We should nevertheless catch this error in BayesianTools in  the future!

**Comment by rtrepos** [comment]
Thanks Florian for your answer. I did not find however what the Z matrix refers to

**Comment by florianhartig** [comment]
see https://github.com/florianhartig/BayesianTools/issues/79

**Comment by florianhartig** [comment]
the z-matrix is the memory of samples that the DEzs is using for the generation of new proposals, see help of the sampler

**Comment by florianhartig** [comment]
OK, I have just pushed a fix that catches the error in the gelmanDiag calculations, and instead gives a message to the user that chains should be run longer
