### ISSUE TITLE
Possible conflict in DREAMzs' pCRupdate and DEpairs

### ISSUE THREAD

**Issue by themisbo** [florianhartig/BayesianTools#167]
Hi,

I recently started using the package and, first of all, I'd like to thank you for your work and effort.

In the the DREAMzs sampler by setting:

- pCRupdate = TRUE

- DEpairs = 3

I am getting the message:
"Error in AdaptpCR(CR, delta, lCR, settings, Npop):
object 'pCR' not found

Could this be a bug or am I missing something on a theoretical level?

Thank you.

**Comment by florianhartig** [comment]
I can't reproduce this, e.g. this runs for me

```
ll <- generateTestDensityMultiNormal(sigma = "no correlation")
bayesianSetup <- createBayesianSetup(likelihood = ll, lower = rep(-10, 3), upper = rep(10, 3))
settings = list(iterations = 10000, pCRupdate = TRUE, DEpairs = 3)
out <- runMCMC(bayesianSetup = bayesianSetup, sampler = "DREAMzs", settings = settings)
```

can you post a reproducible example?

**Comment by themisbo** [comment]
My bad, it looks like I also had a poor choice of startValue for my model and that affected the algorithm.

Sorry for wasting your time.

Thanks for the quick response.

P.S. If I am not mistaken in the DREAMzs documentation, under the argument explanation of  pCRupdate it claims that the default is TRUE, even though it's actually FALSE

**Comment by florianhartig** [comment]
Thanks for the feeback - I'm re-opening this to look at the documentation
