### ISSUE TITLE
Errors on restarting the sampler

### ISSUE THREAD

**Issue by liusongplay** [florianhartig/BayesianTools#171]
The single implementation of runMCMC has been executed successfuly, but errors occur when I want to restart the sampling session.

```
settings = list(iterations = 300000, nCR = 8, gamma = 0, eps = 0, e = 0.05, 
                pCRupdate = TRUE, updateInterval = 10, burnin = 290000, thin = 1, 
                adaptation = 0.6, parallel = NULL, Z = NULL, ZupdateFrequency = 10, 
                pSnooker = 0.1, DEpairs = 2, consoleUpdates = 10, startValue = NULL, 
                currentChain = 1, message  = TRUE)
```

`mcmc <- runMCMC(BayesianSetup, sampler = "DREAMzs", settings)`

`MCMC <- runMCMC(mcmc)`

Here is what the error looks like:
     **"Error in if (any(x < lower)) return(-Inf) : missing value where TRUE/FALSE needed"**

I wonder if there is anything wrong about my codes. It's really uncomfortable for users to check the convergence by himself.

**Comment by florianhartig** [comment]
Hi, was this problem solved or did you close by accident?

**Comment by liusongplay** [comment]
>           Hi, was this problem solved or did you close by accident?

Yes. This problem has been solved successfully.  (see #158 )
