### ISSUE TITLE
References for MCMC samplers

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#18]
I added a bunch of references for the MCMC samplers in the Vignette, Stefan, can you have a look whether this is the actual reference that you used, and also, could you add the references to the help files where appropriate.

Otherwise, I think the vignette is now cleaned up and, while not great, I think it's OK for a first CRAN release.

**Comment by stefan-paul** [comment]
Ok I updated the vignette, https://github.com/florianhartig/BayesianTools/commit/c15185c33e68b4b722fd29262a69ac84f2f97017
Should I also add some information to the description of the sampler in the vignette?

**Comment by florianhartig** [comment]
Yes, that would be great!

**Comment by stefan-paul** [comment]
Done. https://github.com/florianhartig/BayesianTools/commit/34d710dc403f27e3e84ebcc47203b5df0ed52fe8
