### ISSUE TITLE
likelihood function

### ISSUE THREAD

**Issue by fkrauer** [florianhartig/BayesianTools#190]
Hi Florian

I have some issues with the model fit. So just to check my sanity, can you confirm:
The sampler uses the log likelihood (NOT the negative log likelihood, as for example MLE), correct?
Best, Fabienne

**Comment by florianhartig** [comment]
Hi Fabienne, yes, the log likelihood!

**Comment by fkrauer** [comment]
thanks. I was starting to doubt everything I knew...
