### ISSUE TITLE
DEzs error message with missing boundaries

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#20]
If lower / upper are not provided in the prior, I get a cryptic error message 

```
# Create a general prior distribution by specifying an arbitrary density function and a
# corresponding sampling function
density = function(par){
  d1 = dunif(par[1], -2,6, log =TRUE)
  d2 = dnorm(par[2], mean= 2, sd = 3, log =TRUE)
  return(d1 + d2)
}

# The sampling is optional but recommended because the MCMCs can generate automatic starting
# conditions if this is provided
sampler = function(n=1){
  d1 = runif(n, -2,6)
  d2 = rnorm(n, mean= 2, sd = 3)
  return(cbind(d1,d2))
}

prior <- createPrior(density = density, sampler = sampler, 
                     lower = NULL, upper = NULL, best = NULL)


# Use this prior in an MCMC 

ll <- function(x) sum(dnorm(x, log = T)) # multivariate normal ll
bayesianSetup <- createBayesianSetup(likelihood = ll, prior = prior)
out <- runMCMC(bayesianSetup = bayesianSetup)

```

Error in `colnames<-`(`*tmp*`, value = c("LP", "LL", "LPr")) : 
  length of 'dimnames' [2] not equal to array extent 

changing to 

```
prior <- createPrior(density = density, sampler = sampler, 
                     lower = c(-3,-3), upper = c(3,3), best = NULL)
```

Seems to me this is a bug, because a sampling function is provided, so there should be no need for boundaries.

If fixing this, can you have a look to fix this as early as possible? Probably the DEzs wants to access some length or names from the BayesianSetup that depend on the boundaries that are absent in this case. We should take care to fix the problem there, not in the DEzs

**Comment by stefan-paul** [comment]
The problem is that the sampler does not know the number of parameters in the setup if
no boundaries are provided.
bayesianSetup$numPars is 0.

**Comment by florianhartig** [comment]
then the trick would be to see if a sampler is provided, and if so, create a sample to check. I think this is used in other places of the setup.

**Comment by florianhartig** [comment]
Two more things

a) is numPars essential? Should we throw an error if it can't be derived?

b) Even if it is not essential, we should probably notify the user that there is an issue - if it's not essential, better a message than a warning, but some notification would be good, because from the error later an average user will have no idea what the problem was.

**Comment by stefan-paul** [comment]
Wait.. I fixed this. There was already a line to catch possible errors but it missed 
the case if the sampler is provided in the prior.
I'll push it with the other things.

**Comment by stefan-paul** [comment]
Done https://github.com/florianhartig/BayesianTools/commit/06e234464a95816166f83f5b7f96a705dfaa9092 .
