### ISSUE TITLE
Add documentation / references for the Metropolis sampers

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#22]
Stefan, can you check references / documentation for the Metropolis samplers, and add them in Vignette and Help

**Comment by stefan-paul** [comment]
Added most with https://github.com/florianhartig/BayesianTools/commit/9180cf3431774c3f12493caed594dffb3f0e4eba .
Also added some information about the sampler in the vignette.

**Comment by florianhartig** [comment]
I think this is done, thanks!
