### ISSUE TITLE
parallel = n is missing from createBayesianSetup() documentation

### ISSUE THREAD

**Issue by twest820** [florianhartig/BayesianTools#225]
The current documentation for `createBayesianSetup()` indicates only `TRUE` and `FALSE` as valid values for `parallel` (well OK, actually, it indicates the shorthand `T` and `F`). Based on one sentence in the vignette and observations of behavior it looks like `parallel = TRUE` may be accepted for DEzs but doesn't result in concurrent execution of independent chains with `runMCMC(nrChains > 1)` (https://github.com/trotsiuk/r3PG/issues/56). I think the intended default use pattern of DEzs might be something like

```R
n = <a value in the range of 3 up to the number of cores or simultaneous threads supported by the system, inclusive>
mcmcSetup = createBayesianSetup(parallel = n, ...)
mcmcOut = runMCMC(bayesianSetup = mcmcSetup, sampler = "DEzs", settings = list(nrChains = n, ....))
```

From the same sentence in the vignette it appears this may also apply to DREAMzs. But I've only checked DEzs so far.

**Comment by florianhartig** [comment]
OK, my documentation for BayesianSetup says: 

> parallel | parallelization option. Default is F. Other options are T, or "external". See details.

and in details 

> For parallelization, option parallel = T means that an automatic parallelization via a standard R socket cluster is attempted. By default, a copy of your workspace, including DLLs and objects are exporte to the cluster workers. Because this can be very inefficient, you can explictly specify the packages, objects and DLLs that are to be exported via parallelOptions.
> 
> Using parallel = T requires that the function to be parallelized is well encapsulate, i.e. can run on a shared memory / shared hard disk machine in parallel without interfering with each other. For some functions and programs, this is not the case, so that a custom-programmed parallelization is required.
> 
> In this case, and only in this case, you should specify parallel = "external". In this case, it is assumed that the likelihood is programmed such that it accepts a matrix with parameters as columns and the different model runs as rows. It is then up to the user if and how to parallelize this function. This option gives most flexibility to the user, in particular for complicated parallel architecture or shared memory problems.

The parallelization never affects nrChain, this is noted in 

* https://cran.r-project.org/web/packages/BayesianTools/vignettes/BayesianTools.html#reference-on-creating-likelihoods
* https://cran.r-project.org/web/packages/BayesianTools/vignettes/InterfacingAModel.html#speed-optimization-and-parallelization

What is true is that the option to supply n is currently undocumented, I will add this to the help.
