### ISSUE TITLE
Change the name of parameters in output

### ISSUE THREAD

**Issue by NataliaNash** [florianhartig/BayesianTools#233]
Hi there,

I used createBayesianSetup and runMCMC functions and I appreciate it if you could help me about these questions:

1.  plot(out) and MAP(out) commands used the name of par 1, par 2,...how can I change the name of the parameters in output?
2. Is this possible to plot the whole iteration in output? I used 20000 iteration but plot() just shows 1200 iteration.

![Capture](https://user-images.githubusercontent.com/91722306/144423247-2a8f1038-77b8-4c7c-adb6-d61c6ce6bdfe.JPG)

**Comment by NataliaNash** [comment]
Thank you so much Florian!

**Comment by florianhartig** [comment]
Seems resolved, I will close, feel free to re-open if you have follow-up questions.
