### ISSUE TITLE
Internal functions in package index

### ISSUE THREAD

**Issue by stefan-paul** [florianhartig/BayesianTools#24]
Some (or all?) internal functions are listed in the package index
even though they don't have the @export label.
Might be somewhat confusing for the user.

**Comment by florianhartig** [comment]
Can you have a look if there is an option to suppress this?

**Comment by stefan-paul** [comment]
According to the documentation only functions with the 
export label should be exported.
But I'll have another look!

**Comment by stefan-paul** [comment]
Done with https://github.com/florianhartig/BayesianTools/commit/b9d8bc49c63c2be786fbd5591ce7c900c61c84fc .
Just commented out all the roxygen commands for the not-exported functions.
However, I still think that this is somewhat strange. According to the roxygen docs we
did it the right way, so the functions should not have appared in the namespace....

**Comment by florianhartig** [comment]
This seems to be a known problem 

http://stackoverflow.com/questions/41411044/need-to-document-arguments-in-functions-which-are-not-exported-in-r-package

In this one Ben also suggests to use normal comments as we have it now. This here 

http://stackoverflow.com/questions/15892761/do-not-show-function-help-document-in-building-r-package-by-roxygen2

states that 

> http://stackoverflow.com/questions/15892761/do-not-show-function-help-document-in-building-r-package-by-roxygen2

helps - can you check this out, just to know?

**Comment by stefan-paul** [comment]
Ok. I'll have a look tomorrow.

**Comment by stefan-paul** [comment]
Just checked. The '@keywords internal' version creates a help page which can be accessed 
with ?foo. However, the funtion itself does not show in the namespace. 
Regular # instead of the roxygen #' don't create a help page and the
function is not exported in the namespace.
I would tend to use the latter version to truly keep the functions internal.
@florianhartig what's your opinion?

**Comment by florianhartig** [comment]
yes, I agree! Done.
