### ISSUE TITLE
Example for SMC with multiple likelihoods

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#25]
Create a examples that shows how to use the SMC to filter multiple data types /  likelihods, in the sense of

a) create setup (prior + data1)
b) SMC1
c) create new setup (flat prior + data 2) - note, the the prior is not really flat, it's just that if the SMC is initialized with the prior, so you don't want to add the prior again the the BayesianSetup
d) initialize new SMC2 with setup and result from SMC1 as output

(check if this all works as expected, especially the init of d). If that all works, add this to the vignette.

**Comment by florianhartig** [comment]
Hi Tankred, could you add an SMC example with this idea? Maybe the easiest would be to look at a time series that you split in half

**Comment by TankredO** [comment]
7166e4f47f00839093b4650a39c864307989a79a

Added example with multiple likelihoods (split time series in half)
