### ISSUE TITLE
Examples in Vignette with eval = F intentional?

### ISSUE THREAD

**Issue by TahminaMojumder** [florianhartig/BayesianTools#253]
There are several places where eval = F - is this intentional?

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L204

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L225

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L237

https://github.com/florianhartig/BayesianTools/blob/92b3ca9b3398555bd37125c69264ad8c3f3223cb/BayesianTools/vignettes/BayesianTools.Rmd#L287

**Comment by florianhartig** [comment]
Moved to https://github.com/florianhartig/BayesianTools/pull/254
