### ISSUE TITLE
Rejection rates in DEzs

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#28]
I have the experience (Dani and Francesco reporte this as well) that the rejection rate of DEzs in realistic application seems inefficiently high (say, > 95%). I guess the first thing would be to find out why. 

One suspicion of mine is that at least parts of this is due to unreasonable starting points, which leave a trace of unreasonable chain element in memory. I wonder if https://github.com/florianhartig/BayesianTools/issues/8 would improve this

**Comment by checcomi** [comment]
To remove the unreasonable points we could also try to implement in DE the algorithm that is used in DREAM to remove the outliers and limit its use in the burn-in phase to avoid problems in a detailed balance proof.

**Comment by florianhartig** [comment]
Yes, that is another option. 

In any case, we could also use https://github.com/florianhartig/BayesianTools/issues/8 during adaptation only

**Comment by stefan-paul** [comment]
We already have the sampler @checcomi described. 
If you set nCR = 1 and DEpairs = 2 in DREAM then it is 
basically a DE sampler that removes outliers during burn-in.

**Comment by florianhartig** [comment]
good point. I will try this!

**Comment by checcomi** [comment]
@stefan-paul  good!
Does the outlier remover works only in the burn-in?

**Comment by stefan-paul** [comment]
@checcomi yes.

**Comment by florianhartig** [comment]
I'll close this now, this is too diffuse ... most of this is probably addressed by the adaptation issue #87 

As for the rest - if DEzs has low acceptance, it's probably an issue of the settings or of the sampler in general, for the particular function that it is used on.
