### ISSUE TITLE
Passing dotdotdot to likelihood function

### ISSUE THREAD

**Issue by dleutnant** [florianhartig/BayesianTools#30]
Hi Florian,
First, thanks a lot for creating and providing BT! Especially, the implementation of Vrugts' DREAM is very helpful for my work! 

As far as I understand your code, the likelihood function only takes care about a vector (or matrix in case of parallelization) of parameter values. Did you consider to pass an arbitrary list of objects to the logdensity function, such as `ll = logDensity(x, ...)` (aka "dotdotdot")?

Best regards from Münster:)
Dominik

**Comment by florianhartig** [comment]
Hi Dominik,

glad you find BT helpful! 

About the ... -> what would you like to pass to the likelihood?

We discussed whether it would be sensible to let the user pass the data, but then the MCMC needs to store the data somewhere, plus this would break compatibility with optim and sensitivity, so we decided against it.

**Comment by dleutnant** [comment]
Thanks for your quick response!
In my case, the likelihood function calls an external model which basically follows the following structure (in magrittr jargon)

```
LL<- function(x) {
 run_external_model(param = x) %>%
  evaluate_model(.) %>%
  do_post_processing(., alpha = 1.234, beta = 5.678) %>%
  calculate_loglikelihood(.)
}
```

Here, the dummy parameters alpha and beta are set according to the calibration setup and are fixed through the MCMC sampling. So in my case, the following would be ideal:

```
LL <- function(x, ...) {
 run_external_model(param = x) %>%
  evaluate_model(.) %>%
  do_post_processing(., list(...)) %>%
  calculate_loglikelihood(.)
}
```
stats::optim offers a comparable ...	"which passes further arguments fn and gr".

**Comment by florianhartig** [comment]
I see. And then you would want to provide the ... to the runMCMC function I guess?

**Comment by dleutnant** [comment]
exactly!

**Comment by florianhartig** [comment]
hmm .... I guess why not, that should be possible. 

We would have to discuss how we handle restarts, i.e. can the user change this setting if the MCMC is restarted or should we save it, and once it was set for the first time, it cannot be changed any more. 

I'm putting this up as a possible enhancement, not sure when we'll find the time to implement this. 

In the meantime, I guess you can solve your problem with a small wrapper as in 

```
runMyMCMC <- function(alpha, beta, ... ){
likelihood <- function{
...
alpha, beta
}
runMCMC (likelihood, ...)

}
```

**Comment by dleutnant** [comment]
Cool! Thanks!

**Comment by florianhartig** [comment]
OK, guys, I think we should make a decision about this ... I don't want to drag this into the next release.

I'm kind of leaning against implementing this, as it doesn't seem to be a huge problem for the user to simply change the likelihood, or, alternatively (a bit dangerous though), let the likelihood access a global variable that is then changed. 

Providing additional comments in the rumMCMC commands would mean passing them from the rumMCMC to the samplers, to the likelihood calls ... it's not a huge effort, but it's more code that we have to maintain.

Additionally, if we do stuff like the WAIC calculations or other things, the parameters need to be available, so they would need to be stored somewhere. 

Once the stuff is stored, the issue arises that a user might re-use a setup with stored additional parameters in a different context, where they modify again the parameters, in which case we have to throw a warning or whatever. 

It all seems to me as if we create a pretty fragile structure for a small improvement in convenience.

**Comment by florianhartig** [comment]
OK, this is closed
