### ISSUE TITLE
new dll registration recommendation in R 3.4

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#31]
seems since R 3.4.0, dlls are supposed to registered differently - I'm getting following note

```
* checking compiled code ... NOTE
File 'BayesianTools/libs/i386/BayesianTools.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
File 'BayesianTools/libs/x64/BayesianTools.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
```
Should implement solution in http://stackoverflow.com/questions/42313373/r-cmd-check-note-found-no-calls-to-r-registerroutines-r-usedynamicsymbols

**Comment by stefan-paul** [comment]
I just had a look at it. 
Followed the advice in the link and [here](https://ironholds.org/registering-routines/) (which basically is the same). But I still get the same note.
However it seems that on Windows the check sometimes failes to detect the use of registration,
see [here](https://stat.ethz.ch/pipermail/r-devel/2017-February/073755.html).

**Comment by florianhartig** [comment]
sure, why not.

**Comment by stefan-paul** [comment]
Even though I still get the note on my machine it passes the
[TravisCI](https://travis-ci.org/florianhartig/BayesianTools/builds/218794804) test for R:devel.
So I guess it should be done with https://github.com/florianhartig/BayesianTools/commit/8abb28b2b1bb7b2e993a88fc1f466f055bbffb0f .

**Comment by florianhartig** [comment]
Yes, this checks out also with the winbuilder tests. Thanks!
