### ISSUE TITLE
Inconsistency with iter and burnin

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#33]
For the population MCMCs (DE / DREAM), iter is divided by the population size, so that iterations = 3000 with DEzs will run 3 chains a 1000 iterations. 

For the burn-in argument, however, this is not the case, so, for example, iterations = 3000 and burn-in = 2000 produces an error for DEzs.

I would suggest to adapt the burnin to behave in the same way as iterations

**Comment by stefan-paul** [comment]
Good point! Haven't noticed this before.
Done with https://github.com/florianhartig/BayesianTools/commit/df47636f01fc199b0282cfad2dbef8f418ce3a8d .
