### ISSUE TITLE
Create shorthand for samplers

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#35]
Given that we have purged the alternative samplers in https://github.com/florianhartig/BayesianTools/issues/19, we could emulate their functionality by allowing the user to call 

runMCMC(..., sample = "DRAM", ...)

which would then call the Metropolis sampler with standard DRAM settings. This would probably be more convenient for inexperienced users than choosing these settings by hand.

**Comment by TankredO** [comment]
Added shorthands: a573debc18e2ab272cd4cfcef43e23ce35a6e30d
Please let me know if this is working as intended.
