### ISSUE TITLE
check thin argument in getPredictiveIntervals

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#38]
The programming on the thinning in getPredictiveIntervals and related functions doesn't seem to be save / elegant. Revise

**Comment by TankredO** [comment]
The thinning in this function works different to the thinning in getSample etc.. Maybe it would male sense to abstract the thinning in a utility function and use it everywhere.

**Comment by florianhartig** [comment]
I don't think that's necessary, I think thin was simply the wrong word for this, in line with the logic of getSample this could simply be renamed into nSamples.

While you're at it, however, could you check

a) that this works

b) what happens if nSamples is smaller than number of samples available in the chain (might be necessary to catch this in get Sample)

**Comment by TankredO** [comment]
Should be save now: 3b4db45af296028a8269e15ce6ca87da973729ee.
Also, `thin` was renamed to `numSamples` to be consistent with getSample.
