### ISSUE TITLE
Another bug in getSample with numSamples and population chains

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#41]
https://github.com/florianhartig/BayesianTools/commit/99570884fe25c87638dcb1da5608d7d6a7836342 fixed https://github.com/florianhartig/BayesianTools/issues/36 , but brought another bug in getSample to the surface, which currently let's the automatic tests fail. 

I haven't managed to fully comprehend what's going on, but the problem seems to be that the numSamples parameter used in the unit tests hadn't been implemented properly across all possible S3 implementations of getSample

**Comment by TankredO** [comment]
The error seems to happen here:

file: classMcmcSampler.R
function: getSample.mcmcSampler
```R
      # Sample size
      if(thin == 1 && !is.null(numSamples)){
        # This should already be the thinning step?
        sel <- seq(1,dim(temp)[1], len = (floor(numSamples/length(sampler$chain))))
        temp <- temp[sel,] 
      }
      
      #############
      
      if (!is.null(whichParameters)) temp = temp[,whichParameters]
      
      out[[i]] = coda::mcmc(temp, start = start, end = end, thin = thin)
```
I don't really understand what this is supposed to do. Should the thinning be applied such that numSamples determines how many samples collected per chain or from all chains together? (seems like the latter)

The problem that happens here - to my undestanding - is that the chain is already thinned out after  "if(thin == 1 && !is.null(numSamples)){ .... }". In this case the coda::mcmc() function with thinning=1 is only there to create the mcmc object from the temp matrix. However, if that is the intention we need to adjust the end parameter of coda::mcmc, whenever the temp matrix is already thinned.
