### ISSUE TITLE
numSamples rounding

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#42]
getSample(numSamples  = 50) will deliver something > 50, depending on the combinations of nrChains and internal chains, as we ceil the number if we have to divide 50 / chains / internalChains ... we could just leave it like that, I'm just wondering if a user would ever rely on the fact to get exactly 50 back, and if we should thus drop the excess samples at the end?

**Comment by florianhartig** [comment]
Check also what happens if numSamples > available Samples

I would suggest that in this case, we simply return everything that is available

**Comment by TankredO** [comment]
2783b7d4405ce0f6d5dd187f0a775f32cfff73fd
Added checks for thin and numSamples. Further I added a warning if the true number of samples is greater than the requested number of samples.

**Comment by florianhartig** [comment]
see comments in https://github.com/florianhartig/BayesianTools/commit/2783b7d4405ce0f6d5dd187f0a775f32cfff73fd

if excess samples is a problem, we should simply solve the problem except that throwing a warning

**Comment by florianhartig** [comment]
To be honest, I think it's not a big problem at the moment, let's not blow up the code - so I would take the warning out, but add a comment to the help that numSamples can be greater than requested

**Comment by TankredO** [comment]
3b4db45af296028a8269e15ce6ca87da973729ee
Added description to help of getSample that describes the rounding problem and commented out the corresponding warning. Also added checks for 0 and negative thin and numSamples arguments.
