### ISSUE TITLE
Complete author tags

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#44]
@stefan-paul , I noted that we don't have author tags for all functions, can you have a look if all functions that you programmed are tagged, and in particular about the DE / DEzs I wasn't so sure how much is from you and how much from Francesco, in doubt I guess you should add both of you

**Comment by stefan-paul** [comment]
Done with https://github.com/florianhartig/BayesianTools/commit/2d4be3274b422a76429b63b0eac27476cd56f761.
