### ISSUE TITLE
Finalize package for 0.1.2

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#47]
Tankred, if you work today, can you finalize the help things and then run all local tests as well as http://win-builder.r-project.org tests and report back if everything is fine? Note that warnings in the tests are treated as errors, i.e. there must be no errors or warnings.

**Comment by TankredO** [comment]
I will have a look at this in the afternoon. Are there any critical help files you have in mind?

**Comment by florianhartig** [comment]
No, nothing of this was critical - you can just wrap up and complete the rest of the help with 0.1.3 (unless you find a error anywhere)

**Comment by TankredO** [comment]
08c77c9
On my local windows 10 machine everything works fine and the build passes the travis CI tests, too. However, I am not getting an answer email from the winbuilder.r-project.org for an hour now. Is this normal?
