### ISSUE TITLE
Move numSamples to external function

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#49]

**Comment by TankredO** [comment]
e72e4121d8e42215063bf553b96c9e26e933fe91

**Comment by florianhartig** [comment]
Unit tests added? If all works, close the ticket

**Comment by TankredO** [comment]
I will add tests and then close the ticket.

**Comment by TankredO** [comment]
eda395cf162a5f793fc3c5c7877585e122c79298
