### ISSUE TITLE
Extend getSample to coda

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#50]
See started version in new branch https://github.com/florianhartig/BayesianTools/tree/getSample

**Comment by TankredO** [comment]
6a211433953016588b32554527c3b6eafca32f4a
ca095a3c0f5bb91837be64365ba01f90be991fc7

**Comment by florianhartig** [comment]
Hi Tankred,

is this tested and fully functional?

**Comment by florianhartig** [comment]
Unit tests added?

**Comment by TankredO** [comment]
Tests will be added today.

**Comment by stefan-paul** [comment]
I get an error if I try to use the getSample function for coda objects.
At least for coda objects created by the runMCMC function (which shouldn't
be different from any other coda mcmc objects).

```R

# Create setup
ll <- function(x) sum(dnorm(x, log = T))
setup <- createBayesianSetup(ll, lower = c(-10), upper = c(10))
settings <- list(iterations = 1000, adapt = F, optimize = F)

# Run sampler
out <- runMCMC(setup, sampler = "Metropolis", settings = settings)

# Get sample
sam <- getSample(out$codaChain)
``` 

Produces:
```
Error in getSample.matrix(as.matrix(sampler), parametersOnly = parametersOnly,  : 
  object 'includesProbabilities' not found 
```


Defining an boolean object 'includesProbabilities' in the global workspace solves the
issue but I guess it should work without doing so.

Also documentation of the new functionality is missing.

**Comment by TankredO** [comment]
Seems like I introduced this error in 5ea331026f7ff51c3edd3c2f0ac96d2bb5fd0122. The problem is that the methods have different signatures (which they must not have according to cran) and I didn't realize that. I will sort that out as soon as possible.

**Comment by TankredO** [comment]
bf7f4da91293a9dfaf0bba27ab87027fbb2b9c10
should be solved. Documentation is another issue, the "old" methods (getSample.Matrix / getSample.MCMCSampler ....) do not have an own description, so i did not know if that is desired.

**Comment by stefan-paul** [comment]
Yes, it works now (again). Thanks for the fix!
In the description I'd just add that the argument 'sampler' can also
be a coda object.

**Comment by TankredO** [comment]
a35eee6f6f84109c2b70e434534f71bf110b2f0c
