### ISSUE TITLE
error in plotTimeSeriesResults 

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#52]
Reported by Gavan McGrath

Using the example in ?VSEM in the package BayesianTools I'm attempting to iteratively update the prior but find the plotTimeSeriesResults produces the following errors when I extend the VSEM example in BayesianTools.  With the Code below (the errors) I get:
"  Error in quantile.default(x, probs = quantiles[i]) :
  missing values and NaN's not allowed if 'na.rm' is FALSE"

The error appears to come from the function getPredictiveIntervals, specifically the lines:

```
for (i in 1:nrow(predDistr)) {
            predDistr[i, ] = error(mean = pred[i, ], par = parMatrix[i,
                ])
        }
predInt = getCredibleIntervals(sampleMatrix = predDistr,
            quantiles = quantiles)

```
I suspect lower and upper bounds on the parameters are not being enforced leading to a negative standard deviation being passed to rnorm?.
Any suggestions on how to proceed would be welcome.

Code:

#run the example in ?VSEM first then:

```
newPrior = createPriorDensity(out, method = "multivariate",
                              eps = 1e-10,
                              lower = refPars$lower[parSel],
                              upper = refPars$upper[parSel])

bayesianSetup <- createBayesianSetup(likelihood = likelihood,
    prior = newPrior,
    names = rownames(refPars)[parSel] )


out <- runMCMC(bayesianSetup = bayesianSetup, settings = settings) 
plotTimeSeriesResults(sampler = out,
                      model = createPredictions,
                      observed = obs,
                      error = createError,
                      prior = TRUE,
                      main = "Prior predictive")
```

**Comment by TankredO** [comment]
The NaNs are introduced in getPredictiveDistribution (mcmcConfidence.R) when the the model function is applied to the sampled parameters:
```R
getPredictiveDistribution<-function(parMatrix, model, numSamples = 1000){
  
  if (numSamples != F && nrow(parMatrix) > 2*numSamples && !is.null(numSamples) && numSamples > 0){
    sel = round(seq(1,nrow(parMatrix), len = numSamples ))
    parMatrixSel = parMatrix[sel,]
  }else{
    parMatrixSel = parMatrix
  }
  
  run1 = model(parMatrixSel[1,])  # <=== Here 
  
  out = matrix(NA, ncol = length(run1), 
               nrow = nrow(parMatrixSel))
  
  out[1,] = run1
  
  for (i in 2:nrow(parMatrixSel)){
    out[i,] = model(parMatrixSel[i,])  # <=== Here 
  }
  return(out)
}
```

**Comment by florianhartig** [comment]
Hi Gavan,

ok, sorry that this took a bit longer. I think the immediate reason for this error was simply that you provided observed = obs to plotTimeSeriesResults. obs is the whole data frame with 4 outputs. The plotTimeSeriesResults function can only be used for one output, so you have to decide. As you see in the help, we plot for output1, so we use in the example  observed = referenceData[,1].

That being said, while checking your problem, I realized we had two quite annoying bugs in the createPriorDensity function, which is why it took me a bit longer. Long story short, the boundaries were not properly enforced, and the mean was not properly passed on, so this was not good. In my defense, this was supposed to be a quick hack until we have time to implement a better function for density estimation, because the multivariate norma is not particularly well suited for complicated targets anyway, but nevertheless. 

This is fixed in https://github.com/florianhartig/BayesianTools/commit/05e562637126eedf3c1169106ccb53b07f38b73b. Until we have this on CRAN,I would highly recommend installing the development (GitHub) version of the package if you want to use the createPriorDensity function.

**Comment by florianhartig** [comment]
And: thanks for reporting this!
