### ISSUE TITLE
Unregistered symbols warnings

### ISSUE THREAD

**Issue by TankredO** [florianhartig/BayesianTools#53]
With the newest R and Rcpp version we now get the following note when checking the package:
```
File 'BayesianTools/libs/x64/BayesianTools.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
It is good practice to register native routines and to disable symbol
search.
See 'Writing portable packages' in the 'Writing R Extensions' manual.
```

I already tried these solutions:
https://github.com/kbenoit/quanteda/issues/846, 
https://github.com/RcppCore/Rcpp/issues/636,
https://stackoverflow.com/questions/42313373/r-cmd-check-note-found-no-calls-to-r-registerroutines-r-usedynamicsymbols

**Comment by florianhartig** [comment]
Isn't this this old problem https://github.com/florianhartig/BayesianTools/issues/31

Solution doesn't work any more?

**Comment by TankredO** [comment]
1b3d1ff
