### ISSUE TITLE
issues with scale = T in marginalPlot 

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#54]
Run example of VSEM and try marginalPlot(out, scale = T)

```
 Error in plot.default(NULL, ylim = c(0, numPars + 1), type = "n", yaxt = "n",  : 
  object 'xlim' not found 
```

**Comment by florianhartig** [comment]
@TankredO I wanted to do this myself but don't find the time, it's not urgent but if you have time could you have a look at this?

**Comment by TankredO** [comment]
9c8e3ece24d1c52e0f2499185ab578b869c42752
