### ISSUE TITLE
error = NULL in plotTimeSeriesResults

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#55]
Hi Tankred,

since the introduction of the DHARMa plots, error = NULL in plotTimeSeriesResults is not possible any more, but the user should be able to do the posterior predictive without the error distribution, so can you add a switch in the function to not do the other plots if error is not provided.

**Comment by TankredO** [comment]
I can not reproduce the problem if i run VSEMhelp with error set to NULL and plotResiduals to false:

```R
# VSEMhelp ...

# plot prior predictive distribution and prior predictive simulations
plotTimeSeriesResults(sampler = out, model = createPredictions, observed = referenceData[,1],
                      error = NULL, prior = TRUE, main = "Prior predictive", plotResiduals = F)

# plot posterior predictive distribution and posterior predictive simulations
plotTimeSeriesResults(sampler = out, model = createPredictions, observed = referenceData[,1],
                      error = NULL, main = "Posterior predictive", plotResiduals = F)
```

Right now plotResiduals default is TRUE so maybe we should change this?

**Comment by florianhartig** [comment]
Yes, remove the warning and just don't plot them, it's perfectly reasonable that the user wants to look at the posterior predictive distribution without the error

**Comment by florianhartig** [comment]
I still get an error if I remove the error ... did you push these changes - I think the behavior should be like this:

* no error provided, plotResiduals not provided -> normal plot
* error provided, plotResiduals not provided -> plot with residuals
* error not provided, plotResiduals = T -> warning

Also, can you try out the plotTimeSeriesResults with different scalings of the screen - on my screen, the labels for the residuals disappear

**Comment by TankredO** [comment]
Yes, I pushed it to the corresponding branch. I will have a look at the margins.
