### ISSUE TITLE
Checks for CRAN 1.3 release

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#58]
Hi Tankred, once the bug issues are closed I want to push this on CRAN - can you recheck unit tests and run all manual checks to confirm that everything seems fine?

**Comment by TankredO** [comment]
I will as soon as possible.

**Comment by TankredO** [comment]
I ran the manual tests, everything works fine, However, when building the package at my windows 10 desktop pc I get again the unregistered symbols note. On cran the build is passing without a note, I have no idea why and when this happens.

**Comment by stefan-paul** [comment]
@TankredO apparently this happens sometimes on widows machines (see [here](https://stat.ethz.ch/pipermail/r-devel/2017-February/073755.html)). If it passes Travis checks it should be fine.
Hat the same issue with https://github.com/florianhartig/BayesianTools/issues/31 .

**Comment by TankredO** [comment]
I see... weird. Thank you!
