### ISSUE TITLE
marginalLikelihood naming 

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#61]
Apparently, we updated the name for the ML in the return of the marginalLikelihood function to marginalLikelihod, so

exp(M1$ln.m - M2$ln.m)

in the vignette should be exp(M1$marginalLikelihod - M2$marginalLikelihod)

I have changed this now in https://github.com/florianhartig/BayesianTools/commit/8bfbe85cf19f9b628b643bcaac9b3a828335e2ca, but I am wondering if this name is wise, as the values are in fact log values of the ML, as the previous naming suggested.

**Comment by florianhartig** [comment]
rename everywhere to ln.ML

**Comment by TankredO** [comment]
e88dec9e66d9d252464c2988c7b74584e56859bc
