### ISSUE TITLE
Function export

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#62]
Help functions that are not intended for the end user such as sampleEquallySpaced should not be exported ( @export ) - can you go through the help and check only functions intended for package users are exported

**Comment by florianhartig** [comment]
Also, I think we should remove the export of the old MCMC functions (M, AM, ...)? We have already removed them from help / vignette, and as we have deprecated developing them, I see no reason why the end user should see them.

**Comment by florianhartig** [comment]
Unless I hear any protest, I would say Tankred, remove all unnecessary exports and all exports of the old MCMC functions

**Comment by TankredO** [comment]
4033323028405dc9588f870a1124df66eaf92540
