### ISSUE TITLE
Include parameter Rhat in summary function

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#64]
Would be nice to include the per-parameter psf (Rhat) from the GelmanDiag in the summary function as a new collumn

**Comment by TankredO** [comment]
f71b5f001629cbd4fc34ee527e6648bc324c2e82
Added psf as column in the field parameters. Also changed the formatting. Before the output was formatted "by hand" and broke at fields > 8 characters. Now we use  the automatic formatting of the print function for dataframes.
