### ISSUE TITLE
LaTeX formulae in WAIC help

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#75]
The formulae in the help don't render properly, it seems the latex is not recognized. I'm actually not sure if that ever worked, but could you have a look if that can be fixed?

**Comment by TankredO** [comment]
Roxygen's Markdown does not support latex formulae for html output right now. I converted the latex formulae to plain html, which made them a bit ugly, but at least now they are displayed properly.
7617195fb8305294d837d26f9852dbfa38673f07
