### ISSUE TITLE
Unit tests for plots

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#77]
All plot functions should work with all possible objects that can be given to getSample

* BT output
* matrix / data.frame
* coda
...

**Comment by TankredO** [comment]
plotMarginals: b021edbaf98f17e9a8d45c6b11fab1108c1d2746

**Comment by TankredO** [comment]
5d6c5353cabe7de481c8616bfcacc19bde696149 15499ff9cb8bd6a1aae98152a10f517062f49113
Added tests for plotMarginal and trace plot. Both functions now work with bayesianOutput, coda, and matrix objects.
