### ISSUE TITLE
Format for initial values and mixing chains afterwards

### ISSUE THREAD

**Issue by yihsiu** [florianhartig/BayesianTools#78]
Hi Florian,

I wonder could I ask some follow-up questions about setting initial values for chains? 

I have been setting initial values for the chains to avoid the -Inf likelihood issue. It runs well but I still have a few questions about it:

 1) I have a few tests on the input format for the initial values. I assume the format requires estimated parameters to be on columns and sub-chains on rows. For example, if I have 19 parameters to estimate and would like to mix three sub-chains into one MCMC chain (just like the default), the initial values input should be a matrix with 19 columns and 3 rows. 

   And my question is: if I would like to run at least two MCMC chains to calculate Gelman–Rubin diagnostic. How could I assign two different set of  initial values for different MCMC chains? If I run more than two MCMC chains with a set of initial values, does it means that both chains start from the same initial values? 

2) A way I was thinking that might help setting different sets of initial values for different MCMC chains is that: maybe I can run each chain individually with different set of initial values, then mix those chains together after the sampling is done to obtain Gelman–Rubin diagnostic. As I didn't find a function to mix multiple chains after the MCMC sampling in the manual, I wonder is mixing chains afterwards possible in BayesianTools? If multiple chains can run individually, it can largely save computation time too. 

3)   This question is probably not related to above two but I was wondering, if I update a BayesianOutput object with more iterations, would the memory matrix (z matrix) be cleaned out and restarted again? Or it is also kept in the BayesianOutput object?    

4) Another not quite related question but I have been wondering: if I run the model on a multi-cores computer, could running several sub-chains (such as, six sub-chains instead of three the default) for on MCMC chain reduce the iterations it requires to convergent and therefore reduce the time it takes, as the parallel option in createBayesianSetup can seem to distribute the sub-chains over the available cores?  

Sorry for my pile of questions and hope I describe it clear. 

Thank you very much for your help!

Cheers
Yi-Hsiu

**Comment by florianhartig** [comment]
Hi Yi-Hsiu,

sorry for the late reply, I just realized I forgot to answer this question. 

1. Not sure if we speak about the population within one DE-MCMC, or running several of them (e.g. nrChains = 3). If you run a single DE-MCMC, the startvalue will be a matrix. If you run several chains, you see help of runMCMC "Startvalues for sampling with nrChains > 1 : if you want to provide different start values for the different chains, provide them as a list", i.e. you have to provide several matrices as a list

A general consideration about 2-3: you can calculate Gelman-Rubin on a single DE-MCMC run, so you don't have to set nrChains >1, but we recommend running several chains. The explanation of this is somewhat technical. If the DE-MCMC is in equilibrium, the internal chains are independent, and Gelman-Rubin should work, but if it's not, there will be correlation, so it's a bit a hen and egg problem. I would have to write a longer explanation of this. 

2. Yes, this function is available, it's createMcmcSamplerList

3. No, it should be kept. However, it can make sense to restart it, see https://github.com/florianhartig/BayesianTools/issues/79

4. The DE-MCMCs can make use of multicores, but only up to the number of external chains. So, if you run an DE-MCMC with 3 internal chains, you should request parallelization with 3 cores (see BayesianSetup). If you have 8 cores, and want to run 2 of these MCMCs, it would make sense to start 2 R instances, each with 3 cores, and then combine the output afterwards (see question 2)

Best
Florian

**Comment by yihsiu** [comment]
Hi Florian,

Thank you very much for the reply! Yes, all my questions are on DEzs sampler. 

The example #79 is really helpful. That explains my wondering about why running several small chains with smaller iteration number by restarting sampler can generate results different from running a long chain, even when the total iteration number is the same.  

Thanks again for the help!

Best wishes
Yi-Hsiu

**Comment by florianhartig** [comment]
Hi Yi-Hsiu,

glad the comments were useful to you.

However, I am a bit confused by the behavior you describe. The idea of what we programmed is that running several restarts should NOT be different from running a long chain, and that you have to actively re-initialize the z-Matrix at restart, as explained in https://github.com/florianhartig/BayesianTools/issues/79

I have just tried normal restarts in a simple example, and that indeed works as I would have expected, i.e. I see no difference 

```
ll <- generateTestDensityMultiNormal()
bayesianSetup <- createBayesianSetup(likelihood = ll, lower = rep(-10, 3), upper = rep(100, 3))

settings = list(iterations = 10000)
out <- runMCMC(bayesianSetup = bayesianSetup, settings = settings)
plot(out)

settings = list(iterations = 1000)
out <- runMCMC(bayesianSetup = bayesianSetup, settings = settings)
for (i in 1:9) out <- runMCMC(out)
plot(out)
```

Can you confirm that you really get different results if you restart? In this case, it would be nice if you could send us a reproducible example.

Best, F
