### ISSUE TITLE
Update our badges

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#81]
https://github.com/RMHogervorst/badgecreatr

**Comment by florianhartig** [comment]
if you do this, can you also update the text on the main website to reflect our new dev / main branch structure?

**Comment by TankredO** [comment]
75599d6df351c1dd57da43c1cfd223b480f321df

**Comment by TankredO** [comment]
6bd23325e1fb1e774cca51dca9b36141c6584918
