### ISSUE TITLE
Help files for non-exported functions

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#85]
I just saw that Francesco's metropolis functions that we removed from being exported were still in the help / overview of functions.

You need to put @keywords internal to avoid that a help file is displayed, regardless of the export, see https://stackoverflow.com/questions/35801800/exclude-function-from-r-package-manual. 

Tankred, for the samplers, I have don this now, but can you check if there are more non-exported functions that have a help file?

**Comment by TankredO** [comment]
Done with c0c78d5e867c64dd80e81349958f8de32e62d321.
Further, I uncommented the Roxygen/Documentation part of non-exported functions and added '@Keywords internal'. Now they still don't show up in the list of functions, but the documentation is available when needed.
