### ISSUE TITLE
Request for y-axis scale in gelmanDiagnostics()

### ISSUE THREAD

**Issue by woodwards** [florianhartig/BayesianTools#91]
It would be useful to allow manual scaling of the y-axis, since the large early time values of Rhat tend to result in a scale which makes it hard to see how closely Rhat approaches 1.0 at late times.

**Comment by florianhartig** [comment]
The gelmanDiagnostics() function is a convenience function that calls getSample from BT, and then the Gelman diagnostics functions from the coda package. 

... is already used for getSample, so we can't forward graphic parameters to this function, and doing this by hand doesn't seem useful. 

So, the easiest solution to access / change details of these functions is to call getSample by hand with output as a coda object, and then access the options of the respective coda functions. 

```
sample <- getSample(out, coda = T) 
library(coda)
gelman.plot(sample, ylim = c(0,1.5))
```

I will add a hint about this in the help for the next package version.

**Comment by florianhartig** [comment]
actually, we can forward, as long as there are no variable names used in both functions ... Max, can you do this?

**Comment by MaximilianPi** [comment]
done, 31582668f3521ea48e8079685d11123bf489ec9a
