### ISSUE TITLE
plotTimeSeriesResults() doesn't work with par(mfrow)

### ISSUE THREAD

**Issue by woodwards** [florianhartig/BayesianTools#92]
I have been trying to make a page of plotTimeSeriesResults() to export to a png file, using par(mfrow). However plotTimeSeriesResults() seems always to plot in the (1,1) position of the grid, multiple plotTimeSeriesResults()s all lie on top of each other.

**Comment by woodwards** [comment]
It doesn't work with viewport() either. I guess there is some internal plot arrangement going on that is overriding these.

**Comment by woodwards** [comment]
Never mind, I found the source code, which uses par(mfrow).

**Comment by florianhartig** [comment]
yes, if the additional residual diagnostics are plotted, par is called - I guess this is unavoidable. We could maybe add an option to create separate plots, but not sure if many users have a need for this.

**Comment by woodwards** [comment]
You could create the grid plot using cowplot::plot_grid() or something. But once you look at the source code it's easy to work around.
