### ISSUE TITLE
Request for custom x axis labels in plotTimeSeries()

### ISSUE THREAD

**Issue by woodwards** [florianhartig/BayesianTools#95]
I set x=my_x_values but the plot shows x=1:n_data_points. In the source code it looks like the polygon() function is overriding x, because len is set using n_data_points not x?

**Comment by woodwards** [comment]
I think code should be

          plot(x, y=rep(0,len), ylim = ylim, type = "n", xlab = xlab, ylab = ylab, ...)
          if(!is.null(predictionBand)) 
            polygon(c(x,rev(x)),c(predictionBand[1,],predictionBand[2,len:1]),col="moccasin",border=NA)
          # polygon(c(1:len,len:1),c(predictionBand[1,],predictionBand[2,len:1]),col="moccasin",border=NA)
          if(!is.null(confidenceBand)) 
            polygon(c(x,rev(x)),c(confidenceBand[1,],confidenceBand[2,len:1]),col="#99333380",border=NA)    
          # polygon(c(1:len,len:1),c(confidenceBand[1,],confidenceBand[2,len:1]),col="#99333380",border=NA)    
          if(!is.null(predicted)) lines(x, predicted, col = "red")
          if(!is.null(observed)) points(x, observed, col = "black", pch = 3, cex = 0.6)

**Comment by florianhartig** [comment]
Hi Simon,

thanks, we'll have a look at this. 

Best,
F

**Comment by TankredO** [comment]
4622cb6ad880ad7a7cd5a37b252636e73953bb96 Custom x values are now correctly shown in the plot.
