### ISSUE TITLE
Improve documentation on parallelization

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#96]
Given the recent questions about parallelization https://github.com/florianhartig/BayesianTools/issues/89, https://github.com/florianhartig/BayesianTools/issues/72 and https://github.com/florianhartig/BayesianTools/issues/94 , I think we should revisit the documentation of the parallelization. 

I had a look in the vignette, we explain the parallelization of the likelihood, but what we don't have are a few worked-through examples that show the entire setup and the nrChains issue https://github.com/florianhartig/BayesianTools/issues/9

So, what I would propose is to add a section "Multi-core and cluster calculations" in the vignette, which explains and shows a few examples about the practicalities of heavy computing.

**Comment by florianhartig** [comment]
example in createBayesianSetup mit Beispiellikelihood parallel = F, parallel = T, extern

**Comment by MaximilianPi** [comment]
solved 3a17045066fe9592353fe12c53565bf8e4b55ee5
