### ISSUE TITLE
Create plot similar to cumuplot 

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/BayesianTools#97]
Create a plot to show stability of standard estimators, similar to coda:: cumuplot, but with several plots for 

* DIC, WAIC
* Standard coda cumuplot
* psrf

![image](https://user-images.githubusercontent.com/5457753/35809395-c75e30b4-0a88-11e8-94f5-b88caa41f88d.png)

(note: the sense of this is partly diagnostic, partly for teaching / demonstrating that the stability of the estimators differs, and that a psrf of 1.05 does not mean that every estimator is stable )

**Comment by MaximilianPi** [comment]
07be3bbedd210bf9a528e87e19af4c66faeea99f Could you please check it?

**Comment by florianhartig** [comment]
ich bekomme da einen Fehler in der Hilfe wenn ich versuche das Package zu kompilieren

**Comment by florianhartig** [comment]
ps - feature branch besser von dev branchen

**Comment by MaximilianPi** [comment]
Ups, gefunden, sollte jetzt funktionieren...hmm, habe ich eigentlich gemacht

**Comment by MaximilianPi** [comment]
255f0ea3dc40877765446bc986fa12d5424f9dbf with custom parameters for plot functions
