### ISSUE TITLE
Fortran DLL not released after completion of runMCMC() parallel

### ISSUE THREAD

**Issue by woodwards** [florianhartig/BayesianTools#99]
I have a likelihood function bt_likelihood() which includes a call to a Fortran DLL. I parallelised my run with

bt_setup <- createBayesianSetup(likelihood=bt_likelihood, 
                                prior=bt_prior, 
                                names=bt_names, 
                                parallel=T, 
                                parallelOptions=list(dlls=list(BASGRA_DLL))
                                )

runMCMC() runs perfectly.

However, when I try to recompile the DLL I find that R is still using it. Could runMCMC please release/unload the DLL/parallel processes after completion? I can do it with 

  installr::kill_all_Rscript_s() # kills processes left from BT parallel

but this seems a bit heavy handed. Thanks.

**Comment by florianhartig** [comment]
Does this problem only occur with a parallel setup? 

Did you try closing the cluster via BayesianTools::stopParallel (I'm not quite sure if this releases the dlls, but it may)

**Comment by woodwards** [comment]
Thanks florian

stopParallel() does not fix it

Turning off parallel does not seem to fix it. It might actually be a problem with RStudio, I'm not sure.

Thanks

**Comment by florianhartig** [comment]
so, if this always occurs, I'm not sure if the R cluster is the problem at all. 

How do you handle the dll in the normal (non-parallel) run - are you following the normal 

```
dyn.load(x, local = TRUE, now = TRUE, ...)

do stuff

dyn.unload(x)
```

sequence?

**Comment by woodwards** [comment]
Yes exactly. When i do this, I can recompile the DLL without shutting down R/RStudio. But when I use BT I have to shut down RStudio to compile, otherwise the gfortran throws a permission error (sometimes I can get away with restarting R or using installr::kill_all_Rscript_s() but this doesn't always seem to work. It's not a big deal, just a little issue.

**Comment by florianhartig** [comment]
hmm ... so

```
dyn.load(x, local = TRUE, now = TRUE, ...)

createBayesianSetup()
runMCMC()

dyn.unload(x)
```

creates this problem, even if you don't create a parallel BayesianSetup?

**Comment by woodwards** [comment]
Yes seems to. But when i turned off the parallel options in BT, I noticed it was still using multiple cores. Is that correct? I can check again.

**Comment by florianhartig** [comment]
usually the dll will be run on a different core than R, so you may see two cores in use, but it would surprise me if you use more than two.

**Comment by woodwards** [comment]
Does parallel=T in runMCMC(settings=) override parallel=T in runMCMC(bayesianSetup=)?

**Comment by florianhartig** [comment]
I'm not 100% sure, but for the dll, this shouldn't matter. The dll will be exported according to the settings in createBayesianSetup , so if you do 

```
parallel=T,
parallelOptions=list(dlls=list(BASGRA_DLL))
```

you will create an R cluster and the dlls will be exported there, regardless of what you do with runMCMC. 

So, the first question is: does the problem persist if you create a BayesianSetup with parallel = F

**Comment by florianhartig** [comment]
If that is not the case, it's just a matter of shutting down all loaded dlls - try the sequence

```
dyn.load(x, local = TRUE, now = TRUE, ...)

createBayesianSetup( parallel = T)
runMCMC()
stopParallel()

dyn.unload(x)
```

**Comment by florianhartig** [comment]
It may be that stopParallel() does not correctly unload the dlls, but that surprises me because installr::kill_all_Rscript_s() works, but there should be nothing to shut down except for the main r instance after stopParallel() has successfully executed. You are calling stopParallel(yourSetup), right?

**Comment by woodwards** [comment]
Ok that seems to work. I'll let you know if it the problem persists. Thanks!

**Comment by florianhartig** [comment]
I assume this is resolved, closed.

**Comment by woodwards** [comment]
Yes this seems to work, thank you, unless you prematurely exit the run.
